### ISSUE TITLE
Mitigate accidental form submission on desktop browsers

### ISSUE THREAD

**Issue by prashtx** [LocalData/localdata-mobile-web#205] opened 2015-05-05 18:52 UTC
When folks use good old fashioned keyboards, we have reports that they will sometimes hit Enter and accidentally submit an entry prematurely. We should probably prevent Enter from triggering the default form action unless the Submit button has focus.

**Comment by hampelm** [comment] 2015-05-05 19:06
Dupe of #56 from way back 😬

**Closed by hampelm** 2015-05-05 19:06 UTC
Labels: bug
